services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: srawp_app
    restart: always
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3007:3007'
    networks:
      - srawp_network

  db:
    image: postgres:15
    container_name: srawp_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - srawp_network

networks:
  srawp_network:
    driver: bridge

volumes:
  postgres_data:
